### ISSUE TITLE
Any equivalent to Select FOUND_ROWS()

### ISSUE THREAD

**Issue by dlinstedt** [snowflakedb/pdo_snowflake#191]
PostGreSQL has this function: FOUND_ROWS(), as does MySQL

https://dev.mysql.com/doc/refman/8.0/en/information-functions.html#function_found-rows

It seems rather important to know just how many rows were pulled by a SELECT statement.  I'm wondering if Snowflake has anything like this or if this will be implemented in the PHP library any time soon?
Thanks,

**Comment by notkriswagner** [comment]
Hi,

Snowflake currently does not have a FOUND_ROWS() function or an equivalent function. Since FOUND_ROWS() is a SQL function this would be a server-side enhancement and not a client-side enhancement. If you would like to see this function added to Snowflake, please open a ticket with support asking for this feature request.

**Comment by dlinstedt** [comment]
Thank you for the prompt response, I truly appreciate it.  Your team rocks, keep up the great work!  Sincerely, Dan
