### ISSUE TITLE
Qs about "Private Preview"

### ISSUE THREAD

**Issue by kalyanaramansanthanam** [snowflakedb/pdo_snowflake#197]
hi. 
We noticed that the project is marked as "private preview". we have the following questions:

1. Is it safe to start using it?
2. what is the timeline for a GA release?
3. are there plans to add PHP composer support for this library?

**Comment by notkriswagner** [comment]
Hi @kalyanaramansanthanam,

1. It is safe to start using this. Since this is a private preview build, we don't have the same guarantees around fixing issues that we do for other drivers and support for new features will come when time allows. This also means that you may experience some bugs (which you can report here) and we only have support for basic functionality (i.e. no key-pair auth or named parameter binding).

2. There is currently no timeline for a GA release. If having a GA, production ready PDO driver is important to you, please reach out to support expressing your interest in having this driver reach GA. The more customers that are interested in this driver, then the sooner it will be released (theoretically).

3. PHP Composer support isn't on the list of required functionality for GA so we don't have plans to add this right away. Depending on the effort level to add PHP Composer support, we may or may not have this at GA.

**Comment by tomasfejfar** [comment]
ad 3. composer is AFAIK used for userland PHP code. This is a PHP extension. You probably mean PECL (https://pecl.php.net) - that is used to install extensions, right?

**Comment by kalyanaramansanthanam** [comment]
thanks. i will open a support ticket and follow up on the GA release
1 final question about `private preview`: 
since the code is public, we don't need to signup for anything right? in other words, is it same as a `public preview`?

**Comment by notkriswagner** [comment]
That is correct, you don't need to signup for anything
