### ISSUE TITLE
Issue with query being queued in snowflake, never finishing (or never starting)

### ISSUE THREAD

**Issue by tvpmb** [snowflakedb/pdo_snowflake#207]
Hi -

So I've got the pdo connecter implemented. I'm seeing an inconsistency with the queries actually running. What I suspect is happening is there is a heavy query running on the snowflake warehouse, blocking the query I'm trying to run, then the snowflake pdo connector "gives up", but never returns from fetching the query -- even if the return was a failure, it would give me the opportunity to try again.

Has anyone run into this behavior before? FWIW, the connector really works great. Aside from the ? vs :var in the update/insert statements, the connector just works.

Looking for input / ideas on how to handle this situation.

**Comment by notkriswagner** [comment]
Hi @tvpmb ,

Glad the connector is working for you (most of the time)! If you could post logs from the connector as well as environment information (PHP version, OS version, PDO Driver version) that would help in figuring out where things are going wrong since you should get an error message back from the driver if the pdo connector "gives up".

Also in the latest release (v0.2.5 at this time) we have support for named parameters as well as positional. Let me know if that solves your use case.

**Comment by tvpmb** [comment]
@notkriswagner the named parameters could actually help out a lot - i was having issues with data sanitization when using bulk inserts `INSERT INTO table (...,...,...) VALUES (...,...,...),(...,...,...)` so I resorted to inserting 1 by 1, about 1000 times.

**Comment by sfc-gh-igarish** [comment]
To clean up and re-prioritize more pressing bugs and feature requests we are closing all issues older than 6 months as of April 1, 2023. If there are any issues or feature requests that you would like us to address, please create them according to the new templates we have created. For urgent issues, opening a support case with this link [Snowflake Community](https://community.snowflake.com/s/article/How-To-Submit-a-Support-Case-in-Snowflake-Lodge) is the fastest way to get a response.
