### ISSUE TITLE
PHP: SSL peer certificate or SSH remote key was not OK

### ISSUE THREAD

**Issue by tomasotruba** [snowflakedb/pdo_snowflake#306]
On connection I allways receive this error:
ERROR PDO   snowflake_driver.c   71: sqlstate: 08001, msg: curl_easy_perform() failed: SSL peer certificate or SSH remote key was not OK

Appending log file:
[snowflake_20230207092613.txt](https://github.com/snowflakedb/pdo_snowflake/files/10672982/snowflake_20230207092613.txt)

**Comment by oranges13** [comment]
I have this same issue

**Comment by oranges13** [comment]
OK, so the documentation on this is extremely unclear. I was using the identifier in the url before the region as my account ID as it described in the connecting section. We were using an alternate region and I even specified the region directly. But I had to use the entire string before the `.snowflakecomputing.com` INCLUSIVE OF `aws` in order to successfully log in without this error.

e.g. log in url = xxxxxx.us-east-2.aws.snowflakecomputing.com

```php
new PDO('snowflake:account=xxxxxx;region=us-east-2', 'username', 'password'); // Failure

new PDO('snowflake:account=xxxxxx.us-east-2.aws', 'username', 'password'); // success
```

**Comment by Denish-faldu** [comment]
> OK, so the documentation on this is extremely unclear. I was using the identifier in the url before the region as my account ID as it described in the connecting section. We were using an alternate region and I even specified the region directly. But I had to use the entire string before the `.snowflakecomputing.com` INCLUSIVE OF `aws` in order to successfully log in without this error.
> 
> e.g. log in url = xxxxxx.us-east-2.aws.snowflakecomputing.com
> 
> ```
> new PDO('snowflake:account=xxxxxx;region=us-east-2', 'username', 'password'); // Failure
> 
> new PDO('snowflake:account=xxxxxx.us-east-2.aws', 'username', 'password'); // success
> ```
@oranges13 - This saved my day. Spend 1.5 days finding out the solution. Thank you so much.  This should be in the official documentation.

**Comment by sfc-gh-spanaite** [comment]
Thanks for the update @Denish-faldu
I've opened an internal request to get the Readme page updated. With this in mind, I'll close this issue.
